tamanho_inicial_jogador = 50
jogador_velocidade = 5
altura_tela = 500
largura_tela = 800
altura_background = 500
largura_background = 10000
borda_final = largura_background - largura_tela
bandeirinha = 9500
estado_tela_inicial = 0
estado_jogando_nivel = 1
estado_transicao_nivel = 2
estado_vitoria = 3
estado_ranking = 4
transforma_segundos = 1000